- name: Variables in Play Level
  hosts: all
  vars:
    URL: varaible.example.com
  tasks:
    -name: Print URL
     ansible.builtin.debug
       msg: URL = {{URL}}

- name: Varaibles on Play Level
  hosts: all
  vars:
    URL: teja.example.com
  tasks:
    name: Print URL
    ansible.builtin.debug
      msg: URL = {{teja.example.com}}

