- name: Variables in Play Level
  hosts: all
  vars:
    URL: varaible.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
#Note: If you declare a variable in play level all the tasks can access variable.
  taks:
    - name: print one more time
      ansible.builtin.debug:
        msg: URL = {{URL}}


