- name: Demo on loops
  hosts: localhost
  tasks:
    - name: Demo on list values, Each value is string
      ansible.builtin.debug:
        msg: Hello, {{item}}
      loop:
        - Teja
        - Siri
    - name: Demo on list values, Each value is map
      ansible.builtin.debug:
        msg: Hello {{item.name}}, Welcome to {{item.course}} training
      loop:
          - {name: Teja, course: Devops}
          - {name: Siri, course: Nutrition}
