- name: Setup Frontend Componenet
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - frontend

- name: Setup Mongodb Component
  hosts: MONGODB
  become: yes
  tags:
    - mogngodb
  roles:
    - mongodb


- name: Setup Catalogue Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - catalogue

- name: Setup Redis Component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - redis

- name: Setup User Component
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - user

- name: Setup Cart Component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - cart