groups:
  - name: RoboShopAlerts
    rules:
      - alert: DiskUsageAlertWarning
        expr: ceil ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100)  > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High Disk Usage Alert Warning
      - alert: DiskUsageAlertCritical
        expr: ceil ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100)  > 70
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High Disk Usage Alert Critical